[general]
email = "elischwartzman04@gmail.com"

[database]
SUPABASE_URL = "https://xrnfbewtskvfseehcyke.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybmZiZXd0c2t2ZnNlZWhjeWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0OTIyOTQsImV4cCI6MjA3OTA2ODI5NH0.2niXxQhDPNc-jRzY8e_AY-lmQ8_P3nKXPLCiR2D28gI"